export const SEO_DEFAULTS = {
  name: 'Arratech AB',
  title: 'Connect to the Peppol Network | Access Point Solution',
  description: 'Connect to the Peppol Network | Access Point Solution',

  logoPng: '/logos/arratech_logo.png',
  orgLogo: 'https://www.arratech.com/assets/arratech-logo-hor-blue-black.svg',
  orgImage: 'https://www.arratech.com/logos/arratech_logo.png',

  twitter: '@arratech',
  linkedin: 'https://www.linkedin.com/company/arratech',

  category: 'Technology',
  classification: 'Business Software',
  email: 'info@arratech.com',

  keywords: [
    'Arratech',
    'Arratech API',
    'Arratech Peppol',
    'B2B communication',
    'CTC',
    'GDPR compliance',
    'Insomnia',
    'PEPPOL',
    'PEPPOL consultation',
    'PEPPOL demonstration',
    'PEPPOL help',
    'PEPPOL provider',
    'PEPPOL setup',
    'PEPPOL updates',
    'Peppol API',
    'Peppol ID',
    'Peppol Network',
    'SMP',
    'SMP assistance',
    'SMP implementation',
    'SMP integration',
    'SMP showcase',
    'SMP solutions',
    'API testing',
    'Arratech blog',
    'business automation',
    'business inquiry',
    'contact Arratech',
    'customer support',
    'data protection',
    'digital transformation',
    'e-invoicing',
    'e-invoicing company',
    'e-invoicing demo',
    'e-invoicing implementation',
    'e-invoicing news',
    'e-invoicing support',
    'electronic invoicing',
    'how to Peppol',
    'request demo',
    'service agreement',
    'service terms',
    'solution preview',
    'Swedish privacy law',
    'Swedish tech company',
  ],
}
