export const SEO_DEFAULTS = {
  name: 'Lyra',
  title: 'Connect to the Peppol Network | Access Point Solution',
  description: 'Connect to the Peppol Network | Access Point Solution',

  logoPng: '/logos/lyra_logo.png',
  orgLogo: 'https://www.lyra.com/assets/lyra-logo-hor.svg',
  orgImage: 'https://www.lyra.com/logos/lyra_logo.png',

  twitter: '@lyra',
  linkedin: 'https://www.linkedin.com/company/lyra',

  category: 'Technology',
  classification: 'Business Software',
  email: 'info@lyra.com',

  keywords: [
    'Lyra',
    'Lyra API',
    'Lyra Peppol',
    'B2B communication',
    'CTC',
    'GDPR compliance',
    'Insomnia',
    'PEPPOL',
    'PEPPOL consultation',
    'PEPPOL demonstration',
    'PEPPOL help',
    'PEPPOL provider',
    'PEPPOL setup',
    'PEPPOL updates',
    'Peppol API',
    'Peppol ID',
    'Peppol Network',
    'SMP',
    'SMP assistance',
    'SMP implementation',
    'SMP integration',
    'SMP showcase',
    'SMP solutions',
    'API testing',
    'Lyra blog',
    'business automation',
    'business inquiry',
    'contact Lyra',
    'customer support',
    'data protection',
    'digital transformation',
    'e-invoicing',
    'e-invoicing company',
    'e-invoicing demo',
    'e-invoicing implementation',
    'e-invoicing news',
    'e-invoicing support',
    'electronic invoicing',
    'how to Peppol',
    'request demo',
    'service agreement',
    'service terms',
    'solution preview',
    'Swedish privacy law',
    'Swedish tech company',
  ],
}
